### ISSUE TITLE
backing up container with secrets - duplicate mount point

### ISSUE THREAD

**Issue by RomanSPbGASU** [tlaanemaa/backup-docker#28]
Hi

I am trying to use this tool for backing up my gitlab installation deployed with docker-compose. 

docker-compose.yml is like:
```yaml
version: "3.2"

services:
  gitlab:
    image: 'gitlab/gitlab-ee:13.12.12-ee.0'
    container_name: gitlab
...
    volumes:
      - ./config:/etc/gitlab
      - ./logs:/var/log/gitlab
      - volume_data:/var/opt/gitlab
    secrets:
      - private_key
      - certificate

volumes:
  volume_data:

secrets:
  private_key:
    file: some-path...
  certificate:
    file: other-path...
```
When I try to restore the backup with `sudo backup-docker restore gitlab` from the ~/docker.backup directory I get the following error

  ✖ gitlab: (HTTP code 400) unexpected - Duplicate mount point: /run/secrets/private_key 
  
So as I see in output of `docker inspect gitlab` there are really 2 binds to `/run/secrets/private_key`. One in HostConfig.Mounts and another in Mounts. I am not so familiar with docker mount but it can be the cause.

I'll try to make a minimum reproducible configuration if this isn't so clear.
